<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

namespace GPBMetadata;

use Google\Protobuf\Internal\DescriptorPool;

class Chat
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = DescriptorPool::getGeneratedPool();

        if (static::$is_initialized === true) {
            return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            '0acd010a0a636861742e70726f746f120570726f746f22590a0b436861744d657373616765120c0a0474797065180120012809120c0a0466726f6d180220012809120a0a02746f180320012809120f0a07636f6e74656e7418042001280912110a0974696d657374616d7018052001280322410a0a5573657253746174757312100a08757365726e616d65180120012809120e0a066f6e6c696e6518022001280812110a0974696d657374616d7018032001280342120a0570726f746f42094368617450726f746f620670726f746f33'
        ), true);

        static::$is_initialized = true;
    }
}
