<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

namespace Proto;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Chat;

/**
 * Generated from protobuf message <code>proto.ChatMessage</code>
 */
class ChatMessage extends Message
{
    /**
     * "public", "private", "system"
     *
     * Generated from protobuf field <code>string type = 1;</code>
     */
    protected $type = '';

    /**
     * Sender username
     *
     * Generated from protobuf field <code>string from = 2;</code>
     */
    protected $from = '';

    /**
     * Receiver username (for private)
     *
     * Generated from protobuf field <code>string to = 3;</code>
     */
    protected $to = '';

    /**
     * Generated from protobuf field <code>string content = 4;</code>
     */
    protected $content = '';

    /**
     * Generated from protobuf field <code>int64 timestamp = 5;</code>
     */
    protected $timestamp = 0;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type string $type
     *              "public", "private", "system"
     * @type string $from
     *              Sender username
     * @type string $to
     *              Receiver username (for private)
     * @type string $content
     * @type int|string $timestamp
     *                  }
     */
    public function __construct($data = null)
    {
        Chat::initOnce();
        parent::__construct($data);
    }

    /**
     * "public", "private", "system"
     *
     * Generated from protobuf field <code>string type = 1;</code>
     *
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * "public", "private", "system"
     *
     * Generated from protobuf field <code>string type = 1;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, true);
        $this->type = $var;

        return $this;
    }

    /**
     * Sender username
     *
     * Generated from protobuf field <code>string from = 2;</code>
     *
     * @return string
     */
    public function getFrom()
    {
        return $this->from;
    }

    /**
     * Sender username
     *
     * Generated from protobuf field <code>string from = 2;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setFrom($var)
    {
        GPBUtil::checkString($var, true);
        $this->from = $var;

        return $this;
    }

    /**
     * Receiver username (for private)
     *
     * Generated from protobuf field <code>string to = 3;</code>
     *
     * @return string
     */
    public function getTo()
    {
        return $this->to;
    }

    /**
     * Receiver username (for private)
     *
     * Generated from protobuf field <code>string to = 3;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setTo($var)
    {
        GPBUtil::checkString($var, true);
        $this->to = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string content = 4;</code>
     *
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Generated from protobuf field <code>string content = 4;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, true);
        $this->content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 5;</code>
     *
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 5;</code>
     *
     * @param  int|string  $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }
}
