<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

namespace Proto;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Chat;

/**
 * Generated from protobuf message <code>proto.UserStatus</code>
 */
class UserStatus extends Message
{
    /**
     * Generated from protobuf field <code>string username = 1;</code>
     */
    protected $username = '';

    /**
     * Generated from protobuf field <code>bool online = 2;</code>
     */
    protected $online = false;

    /**
     * Generated from protobuf field <code>int64 timestamp = 3;</code>
     */
    protected $timestamp = 0;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type string $username
     * @type bool $online
     * @type int|string $timestamp
     *                  }
     */
    public function __construct($data = null)
    {
        Chat::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string username = 1;</code>
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Generated from protobuf field <code>string username = 1;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, true);
        $this->username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool online = 2;</code>
     *
     * @return bool
     */
    public function getOnline()
    {
        return $this->online;
    }

    /**
     * Generated from protobuf field <code>bool online = 2;</code>
     *
     * @param  bool  $var
     * @return $this
     */
    public function setOnline($var)
    {
        GPBUtil::checkBool($var);
        $this->online = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 3;</code>
     *
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 3;</code>
     *
     * @param  int|string  $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }
}
