[program:agriverse-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/wanmin/1.Work/03.Project/2026/Orchestrix/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=wanmin
numprocs=2
redirect_stderr=true
stdout_logfile=/home/wanmin/1.Work/03.Project/2026/Orchestrix/storage/logs/worker.log
stopwaitsecs=3600
stopsignal=QUIT

[program:agriverse-scheduler]
process_name=%(program_name)s
command=php /home/wanmin/1.Work/03.Project/2026/Orchestrix/artisan schedule:run --verbose --no-interaction
autostart=true
autorestart=true
user=wanmin
redirect_stderr=true
stdout_logfile=/home/wanmin/1.Work/03.Project/2026/Orchestrix/storage/logs/scheduler.log
