name: Deploy Orchestrix

on:
  push:
    branches:
      - module/AgriVerse

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: Configure VPS

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}

          script: |
            cd /home/deployer/Orchestrix

            git pull origin main

            podman restart orchestrix-php
            podman restart orchestrix-nginx

            echo "Deploy completed"
